"use client";

import { useEffect } from "react";

/**
 * Registers the service worker generated by @ducanh2912/next-pwa (production).
 * In development, SW is disabled so HMR stays clean.
 */
export function PwaRegister() {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") return;
    if (!("serviceWorker" in navigator)) return;

    const register = async () => {
      try {
        await navigator.serviceWorker.register("/sw.js", { scope: "/" });
      } catch {
        // SW optional — ignore registration failures
      }
    };

    void register();
  }, []);

  return null;
}
